### ISSUE TITLE
Support for u64 elements in tuples

### ISSUE THREAD

**Issue by fmartini** [bluejekyll/foundationdb-rs#117]
According to Apple's [documentation](https://github.com/apple/foundationdb/blob/master/design/tuple.md) the tuple layer should be able to support u64 elements:

> 0x1c is an 8 byte positive number

Unless i am mistaken the Rust client currently does not support that.

**Comment by bluejekyll** [comment]
hm, you appear to be correct. It shouldn't be hard to add: https://github.com/bluejekyll/foundationdb-rs/blob/master/foundationdb/src/tuple/element.rs

I can't remember our decision around this at this point, basically we have the option of supporting all the smaller usize/isize types as well. I think it just never was completed.
