### ISSUE TITLE
Segfault when pending future dropped

### ISSUE THREAD

**Issue by dae** [bluejekyll/foundationdb-rs#136]
I've fixed this in https://github.com/bluejekyll/foundationdb-rs/issues/135, but the issue exists in the stable release as well. If others are experiencing segfaults in production, they may wish to backport this:

https://github.com/dae/foundationdb-rs/commit/4506c5126dc58c50054d60c433c500fa6584fb9a

**Comment by Speedy37** [comment]
I backported your fix.
