### ISSUE TITLE
Build broken on linux

### ISSUE THREAD

**Issue by yjh0502** [bluejekyll/foundationdb-rs#22]
It seems that `bindings.rs` is not working for linux. Here's my `bindings.rs` generated from linux environment: https://gist.github.com/yjh0502/9c25ed2e7d1caf8a2792c94aa26a3f3d

 - It seems that bindgen creates `#[link_name = ".."]` clause for darwin.
 - pthread-related symbols are included in committed `bindings.rs`, which does not exists on linux bindings.

**Comment by bluejekyll** [comment]
For now I’ll rollback the checked in bindings file and we can revisit in the future.

**Comment by yjh0502** [comment]
@bluejekyll It seems that bindings from linux works fine on macOS. I'll send a PR with linux bindings.

**Comment by yjh0502** [comment]
Fixed by https://github.com/bluejekyll/foundationdb-rs/pull/23
