### ISSUE TITLE
Implement FoundationDB tutorial as example

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/foundationdb-rs#31]
https://apple.github.io/foundationdb/class-scheduling-java.html

**Comment by yjh0502** [comment]
It seems that tuple layer should be implemented first: https://github.com/bluejekyll/foundationdb-rs/issues/35

**Comment by bluejekyll** [comment]
Yeah, I started working on a Tuple as part of this... I will break that out for a separate review. Are you already doing that?
