### ISSUE TITLE
Higher-layer API: Tuple

### ISSUE THREAD

**Issue by yjh0502** [bluejekyll/foundationdb-rs#35]
Reference implementation in Go:
https://github.com/apple/foundationdb/blob/master/bindings/go/src/fdb/tuple/tuple.go

**Comment by Myrannas** [comment]
I was working on wrapping the foundation db client separately, but given the quality of the bindings you have been working on that looks a bit redundant now :). 

I had however spent a bit of time building out tuple support and packaging it in a library (https://github.com/Myrannas/binary-tuples / https://crates.io/crates/binary_tuples). It is still missing a couple of features (like big int support + version timestamp support), but should be compatible with other implementations

It is my first rust library so it might be a little rough around the edges - but if nothing else may be a good starting point.

**Comment by bluejekyll** [comment]
I’m not sure about depending on something so important to the library as an external dependency. Would you be interested in contributing that to this project?

**Comment by yjh0502** [comment]
@bluejekyll I just landed #40 by myself, because it seems to blocking your side of work. I'll merge #41 after test finishes, as it is a bug fix.

**Comment by bluejekyll** [comment]
Excellent. Thank you.

**Comment by Myrannas** [comment]
Yep, api in #40 looks pretty nice. Nice work.
