### ISSUE TITLE
Implement HCA

### ISSUE THREAD

**Issue by yjh0502** [bluejekyll/foundationdb-rs#44]
https://github.com/apple/foundationdb/blob/master/bindings/go/src/fdb/directory/allocator.go

Implement HCA(high contention allocator), which is a building block for directory layer. There is a `hca` test on `bindingtester`[1] so we can test our implementation with the tester.

[1] https://github.com/apple/foundationdb/blob/master/bindings/bindingtester/run_tester_loop.sh#L12-L13

related: https://github.com/bluejekyll/foundationdb-rs/issues/27

**Comment by yjh0502** [comment]
We can start working on this after following PR: #54, #50

**Comment by pH14** [comment]
This can be closed now

**Comment by bluejekyll** [comment]
Cool, thanks.
