### ISSUE TITLE
tuple: Support Rust-style nested tuple

### ISSUE THREAD

**Issue by yjh0502** [bluejekyll/foundationdb-rs#49]
https://github.com/bluejekyll/foundationdb-rs/pull/47#issuecomment-385746621

**Comment by bluejekyll** [comment]
I think there is nothing to do here... There is one thing that would be cool, but I'm not sure what we can do here, right now you can't decode into something that's comparible with borrowed tuples, example:

`("str", (4,2)).encode_to_vec() == ("str".to_string(), (4,2)).encode_to_vec()`

but this is not true:

`("str", (4,2)) != <(String, (i64, i64))>.decode_full(&[...])`

Not sure what we can do there...

**Comment by rushmorem** [comment]
> Right now you can't decode into something that's comparable with borrowed tuples

This is a limitation from how Rust compares tuples.

```rust
("str", (4,2)) != ("str".to_string(), (4,2))
```

**Comment by bluejekyll** [comment]
I think we should drop the single tuple variant generate in the tuple module: `(0 T0)`

It would remove this confusion: as far as I can tell `(1,).encode() == 1.encode()`, we really need to validate that. Especially b/c I'm fairly certain that `(1, (1,)).encode() != (1, 1).encode()` and that's a little awkward...
