### ISSUE TITLE
tuple: split `Single` to `SingleEncode`/`SingleDecode`

### ISSUE THREAD

**Issue by yjh0502** [bluejekyll/foundationdb-rs#53]
In current implementation, `Single` requires both encoding and decoding, so we cannot support reference type for `Single`, for example, we cannot encode `Single` for `&str`. The limitation is annoying while working with rust-style tuple.

```rust
// good
let tup: (String, String) = Tuple::decode(data)?;

// not working, because &str cannot implements `Single`
// let data = Tuple::encode(&("hello", "world"));

// working but ugly
let data = Tuple::encode(&("hello".to_owned(), "world".to_owend()));
```

We can fix the problem by introducting `SingleEncode`/`SingleDecode` instead of `Single`.

**Comment by rushmorem** [comment]
I've been following the development of this library closely. I see "Single" come up a lot. Would it make sense to extract such things into a `single` module? Instead of `{SingleEncode, SingleDecode}` we could then have `single::{Encode, Decode}`.

**Comment by bluejekyll** [comment]
Single is a single item of a Tuple. Technically they are both part of the tuple module right now. But yes, I think moving single its own module might make that cleaner. We’re not 100% on the naming yet, btw.

**Comment by rushmorem** [comment]
I see, thanks for the explanation. You guys are moving at a tremendous pace. I wish I could chip in right now, but even if I could I would probably just slow you down anyway.

**Comment by bluejekyll** [comment]
That’s all @yjh0502 

I can’t keep pace. I started it and then he basically took it over :)

I add my reviews and little bits here and there.

**Comment by rushmorem** [comment]
I've started working on this. I should have a PR ready shortly.
