### ISSUE TITLE
Evaluate lifetimes of borrow data in transaction before commit

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/foundationdb-rs#55]
Currently we passed references into the methods on Transaction, do these borrows actually need to live until commit? Or are they copied into the transaction so that what we have is safe?

**Comment by yjh0502** [comment]
It seems to be copied into the future object before returns.

https://github.com/apple/foundationdb/blob/master/bindings/java/fdbJNI.cpp#L746-L750

**Comment by bluejekyll** [comment]
Yes. The java definitely implies that. If you’re confident we have the correct pattern here, we can close this.

**Comment by yjh0502** [comment]
I dig into the foundationdb just to make sure.

Here's transaction impl, which implements `ITransaction`
https://github.com/apple/foundationdb/blob/master/fdbclient/ThreadSafeTransaction.actor.cpp#L148

`Key` is `Standalone<KeyRef>`
https://github.com/apple/foundationdb/blob/master/fdbclient/FDBTypes.h#L255

and `KeyRef` is same with `StringRef`
https://github.com/apple/foundationdb/blob/master/fdbclient/FDBTypes.h#L32

which copies data on constructor
https://github.com/apple/foundationdb/blob/master/flow/Arena.h#L398

BTW it's nearly impossible for me to be familiar with c++ codebase...

**Comment by bluejekyll** [comment]
Thank you for the due diligence. And I agree, C++ has gotten to a point where I can’t follow it either :)
