### ISSUE TITLE
Can we use `uuid::Uuid`?

### ISSUE THREAD

**Issue by rushmorem** [bluejekyll/foundationdb-rs#61]
Is there any particular reason we have a custom `Uuid` type instead of just using the one from the `uuid` crate?

**Comment by yjh0502** [comment]
I think we could add uuid as a optional dependency, as postgres does.

https://github.com/sfackler/rust-postgres/blob/master/postgres-shared/Cargo.toml

**Comment by rushmorem** [comment]
Making it optional makes it possible to support alternative implementations in future in a backwards compatible way, if such a need ever arises. Also some people prefer libraries with as few dependencies as possible. Making external dependencies like that optional, makes it possible for them to turn them off when they don't need them. Considering that it's trivial to implement it as optional, I don't really see any reason not to. We can activate it by default.
