### ISSUE TITLE
impl `Sync`/`Send` for `Cluster`/`Database`?

### ISSUE THREAD

**Issue by yjh0502** [bluejekyll/foundationdb-rs#72]
It seems that C API is thread-safe unless explicitly mentioned.
https://github.com/apple/foundationdb/blob/master/fdbclient/ThreadSafeTransaction.actor.cpp#L30-L31

Rust raw pointers are not `Sync`/`Send` by default so `Database` cannot be sent to other thread although `DatabaseInner` is wrapped by `std::sync::Arc`. We can fix the problem by marking `DatabaseInner` and friends as `Sync`/`Send` explicitly.

**Comment by bluejekyll** [comment]
This is done, yest?

**Comment by yjh0502** [comment]
Yes
