### ISSUE TITLE
Is it okay to allow converting an element to a single-element tuple implicitly?

### ISSUE THREAD

**Issue by rushmorem** [bluejekyll/foundationdb-rs#82]
https://github.com/bluejekyll/foundationdb-rs/pull/78#issuecomment-387089309

**Comment by rushmorem** [comment]
@bluejekyll in https://github.com/bluejekyll/foundationdb-rs/pull/78#issuecomment-387230049

> We need to validate this, but as far as I can tell `(1,).encode() == 1.encode()`, but we really need to validate that. Especially b/c I'm fairly certain that `(1, (1,)).encode() != (1, 1).encode()` and that's a little awkward...

**Comment by rushmorem** [comment]
I like that. However, I see a lot of examples with single element tuples in FDB documentation. I'm not sure whether they are supposed to be encoded differently from non-tuple values.

**Comment by bluejekyll** [comment]
Ok, based on this comment, with python generated binary slices: https://github.com/bluejekyll/foundationdb-rs/pull/77#discussion_r186330604

I added two test cases too #83: 

https://github.com/bluejekyll/foundationdb-rs/blob/bbf3241f634ce8d91c961db5712b9daa0a7e9d1c/foundationdb/src/tuple/mod.rs#L271-L277

and

https://github.com/bluejekyll/foundationdb-rs/blob/bbf3241f634ce8d91c961db5712b9daa0a7e9d1c/foundationdb/src/tuple/mod.rs#L303-L309

Which. If you look at those encodings in python, and from that comment, there is no nested tuple markers for the top level tuple. So this is correct at that point.

I think we still need to verify what happens with the single inner tuple...

**Comment by yjh0502** [comment]
Here's some nested tuple examples,

```
>>> [ord(x) for x in fdb.tuple.pack((1,(1,)))]
[21, 1, 5, 21, 1, 0]
>>> [ord(x) for x in fdb.tuple.pack( (1,(1,(1,))) )]
[21, 1, 5, 21, 1, 5, 21, 1, 0, 0]
>>> [ord(x) for x in fdb.tuple.pack( (1,(1,),(1,)) )]
[21, 1, 5, 21, 1, 0, 5, 21, 1, 0]
>>>
```

**Comment by bluejekyll** [comment]
So I guess for maximal compatibility we’ll need single tuple. Oh well, I think the new depth feature on tuple encoding will deal with this fine. I’ll add single tuple back.
